package com.lenardjensen;

import com.lenardjensen.impl.xivapiConnection;

import java.io.IOException;

/**
 * This class will contain the general API handling and store any necessary data
 */
public class xivapi {

	// An API key is not always required but recommended when using a higher throughput
	private boolean validKeyProvided;
	private String apiKey;

	private xivapiConnection apiConnection;

	/**
	 * Constructor for the API access
	 */
	public xivapi() {
		apiConnection = new xivapiConnection();
	}

	/**
	 * Constructor for the API access
	 * @param key API key from the xivapi dev page
	 * @throws IOException Exception thrown when connection could not be established with the key
	 */
	public xivapi(String key) throws IOException {
		apiConnection = new xivapiConnection();
		setApiKey(key);
	}

	/**
	 * Set the key for API access
	 * Will also check if the provided key was valid and sets the matching variable
	 * Setting an empty key will cause the API to make requests without any keys
	 * @param key Key generated by the dev page of the API
	 */
	public void setApiKey(String key) throws IOException {
		apiKey = key;
		validKeyProvided = apiConnection.keyIsValid(key);
	}

	/**
	 * Returns the currently set API key
	 * @return The current key
	 */
	public String getApiKey() {
		return apiKey;
	}

	/**
	 * A quick check if there is currently a key provided
	 * @return True, if a valid key was provided
	 */
	public boolean apiKeyIsValid() {
		// We dont run the validity check here
		// because a key that was valid when it was set should stay valid
		return validKeyProvided;
	}

}
