package de.lenardjensen;

import de.lenardjensen.impl.XivapiConnection;
import org.json.JSONObject;

import java.io.IOException;
import java.util.List;

/**
 * This class will contain the general API handling and store any necessary data
 */
public class Xivapi {

	// An API key is not always required but recommended when using a higher throughput
	private boolean validKeyProvided;
	private String apiKey;

	private XivapiConnection apiConnection;

	/**
	 * Constructor for the API access
	 */
	public Xivapi() {
		apiKey = "";
		validKeyProvided = false;
		apiConnection = new XivapiConnection();
	}

	/**
	 * Constructor for the API access
	 * @param key API key from the Xivapi dev page
	 * @throws IOException Exception thrown when connection could not be established with the key
	 */
	public Xivapi(String key) throws IOException {
		apiConnection = new XivapiConnection();
		setApiKey(key);
	}

	/**
	 * Returns information about a specific Free Company using the Lodestone ID
	 * @param id FFXIV Lodestone ID
	 * @return JSON Object with FC information
	 * @throws IOException Exception thrown when something happened with the connection
	 */
	public JSONObject getFCByID(String id) throws IOException {
		return getFCByID(id, false, false);
	}

	/**
	 * Returns information about a specific Free Company using the Lodestone ID
	 * @param id FFXIV Lodestone ID
	 * @param extended Whether the response should include more detailed info
	 * @param getMember Set to true if output should contain info about FC members
	 * @return JSON Object with FC information
	 * @throws IOException Exception thrown when something happened with the connection
	 */
	public JSONObject getFCByID(String id,  boolean extended, boolean getMember) throws IOException {
		StringBuilder paramBuilder = new StringBuilder();

		if(extended) {
			paramBuilder.append("extended=1&");
		}

		if(getMember) {
			paramBuilder.append("data=FCM");
		}

		return apiConnection.getRequestOutput("freecompany/" + id + "?" + paramBuilder.toString(), apiKey);

	}

	/**
	 * Returns basic information about a character
	 * @param id FFXIV Lodestone ID
	 * @return JSON Object with basic character data
	 * @throws IOException Exception thrown when something happened with the connection
	 */
	public JSONObject getCharByID(int id) throws IOException {
		return apiConnection.getRequestOutput("character/"+id, apiKey);
	}


	/**
	 * Optional parameter enums for the character request
	 * More info on: https://xivapi.com/docs/Character#character
	 */
	public enum dataParams{AC, MIMO, CJ, FR, FC, FCM, PVP}

	/**
	 * Returns basic informations about a character
	 * @param id FFXIV Lodestone ID
	 * @param extended Whether the response should include more detailed info
	 * @param data Receive more than just character data
	 * @return JSON Object with basic character data
	 * @throws IOException Exception thrown when something happened with the connection
	 */
	public JSONObject getCharByID(int id, boolean extended, List<dataParams> data) throws IOException {
		StringBuilder paramBuilder = new StringBuilder();

		if(extended) {
			paramBuilder.append("extended=1&");
		}

		if(!data.isEmpty()) {
			paramBuilder.append("data=");
			for(dataParams param : data) {
				paramBuilder.append(param.name()).append(",");
			}
		}

		return apiConnection.getRequestOutput("character/" + id + "?" + paramBuilder.toString(), apiKey);
	}

	/**
	 * Set the key for API access
	 * Will also check if the provided key was valid and sets the matching variable
	 * Setting an empty key will cause the API to make requests without any keys
	 * @param key Key generated by the dev page of the API
	 * @throws IOException If there was an error with the connection itself
	 */
	public void setApiKey(String key) throws IOException {
		apiKey = key;
		validKeyProvided = apiConnection.keyIsValid(key);
	}

	/**
	 * Returns the currently set API key
	 * @return The current key
	 */
	public String getApiKey() {
		return apiKey;
	}

	/**
	 * A quick check if there is currently a key provided
	 * @return True, if a valid key was provided
	 */
	public boolean apiKeyIsValid() {
		// We dont run the validity check here
		// because a key that was valid when it was set should stay valid
		return validKeyProvided;
	}

}
